default:
  properties:
    proxy.enabled: false
    proxy.ip: 127.0.0.1
    proxy.port: 9000
    webdriver.defaultTimeout: 10
    page.title.timeout: 30
    thread.count: 3
    allure.report: true
    allure.create.enviroment: true
  contexts: [chrome]
